#!/usr/bin/env python3
"""Generate the SDK 1.48 shim's sources from Valve's steam_api.json (downloaded at build time, never committed).

Usage: gen.py <steam_api.json> <outdir>   writes <outdir>/flat148.cpp and <outdir>/isteamtv148.h

flat148.cpp = Steamworks SDK 1.48's flat C API, compiled against 1.48's own C++ headers:
  interface method  -> self->Method(args)              (1.48 class decl => 1.48 vtable slot)
  accessor          -> the header's inline accessor     (SteamInternal_ContextInit + FindOrCreate*Interface, 1.48 version string)
  struct method     -> self->Method(args) / placement new for Construct
steam_api_flat.h is included too, so every definition must match Valve's 1.48 flat declaration
exactly or the build fails. check_abi.py compares the result against Valve's own 1.48 library.
"""
import json, os, sys

api = json.load(open(sys.argv[1]))
OUTDIR = sys.argv[2]
os.makedirs(OUTDIR, exist_ok=True)

# Declared in steam_api_flat.h 1.48 but not in its C++ header: see manual.cpp.
HANDWRITTEN = {'SteamAPI_SteamNetworkingIdentity_SetXboxPairwiseID', 'SteamAPI_SteamNetworkingIdentity_GetXboxPairwiseID'}
TO_CPP = {'uint64_steamid': 'CSteamID({})', 'uint64_gameid': 'CGameID({})'}
FROM_CPP = {'uint64_steamid': '.ConvertToUint64()', 'uint64_gameid': '.ToUint64()'}


def flat_param(p):
    return f"{p.get('paramtype_flat', p['paramtype'])} {p['paramname']}"


def call_arg(p):
    flat = p.get('paramtype_flat')
    if flat is None or flat == p['paramtype']:
        return p['paramname']
    return TO_CPP[flat].format(p['paramname'])  # KeyError = a flat type we don't know how to convert: stop


def wrapper(selftype, m):
    params = [f'{selftype}* self'] + [flat_param(p) for p in m['params']]
    ret = m.get('returntype_flat', m['returntype'])
    args = ', '.join(call_arg(p) for p in m['params'])
    name = m['methodname']
    if name == 'Construct':
        body = f'new (self) {selftype}();'
    else:
        expr = f'self->{name}({args})'
        if ret != m['returntype']:
            expr += FROM_CPP[ret]
        body = expr + ';' if ret == 'void' else f'return {expr};'
    return f"SHIM {ret} {m['methodname_flat']}( {', '.join(params)} ) {{ {body} }}"


def find(kind, key, name):
    return next(x for x in api[kind] if x[key] == name)


# ISteamTV (STEAMTV_INTERFACE_V001) is in 1.48's steam_api.json/steam_api_flat.h, but its header is
# missing from Facepunch's vendored SDK copy: recreate it from the JSON, methods in JSON (= vtable) order.
tv = find('interfaces', 'classname', 'ISteamTV')
region = find('structs', 'struct', 'SteamTVRegion_t')
behavior = find('enums', 'enumname', 'ESteamTVRegionBehavior')
tv_h = [
    '// GENERATED by gen.py from steam_api.json - do not edit.',
    '#pragma once',
    '#include "steam/steam_api.h"',
    'struct SteamTVRegion_t { ' + ' '.join(f"{f['fieldtype']} {f['fieldname']};" for f in region['fields']) + ' };',
    'enum ESteamTVRegionBehavior { ' + ' '.join(f"{v['name']} = {v['value']}," for v in behavior['values']) + ' };',
    'class ISteamTV',
    '{',
    'public:',
    *(f"\tvirtual {m['returntype']} {m['methodname']}( {', '.join(p['paramtype'] + ' ' + p['paramname'] for p in m['params'])} ) = 0;"
      for m in tv['methods']),
    '};',
    f'#define STEAMTV_INTERFACE_VERSION "{tv["version_string"]}"',
    'inline ISteamTV *SteamTV();',
    'STEAM_DEFINE_USER_INTERFACE_ACCESSOR( ISteamTV *, SteamTV, STEAMTV_INTERFACE_VERSION );',
]
open(os.path.join(OUTDIR, 'isteamtv148.h'), 'w').write('\n'.join(tv_h) + '\n')

out = [
    '// GENERATED by gen.py from steam_api.json - do not edit.',
    '#include <new>',
    '#include "isteamtv148.h"  // must precede steam_api_flat.h',
    '#include "steam/steam_api_flat.h"',
    '#include "steam/steam_gameserver.h"',
    '#include "steam/steamdatagram_tickets.h"',
    '#define SHIM extern "C" __attribute__((visibility("default")))',
    '',
]
n = {'method': 0, 'accessor': 0, 'struct': 0}
for i in api['interfaces']:
    cls = i['classname']
    out.append(f'// {cls}')
    for a in i.get('accessors') or []:
        out.append(f"SHIM {cls} *{a['name_flat']}() {{ return {a['name']}(); }}")
        n['accessor'] += 1
    for m in i['methods']:
        out.append(wrapper(cls, m))
        n['method'] += 1
for s in api['structs']:
    for m in s.get('methods') or []:
        if m['methodname_flat'] in HANDWRITTEN:
            continue
        out.append(wrapper(s['struct'], m))
        n['struct'] += 1

open(os.path.join(OUTDIR, 'flat148.cpp'), 'w').write('\n'.join(out) + '\n')
print('generated', n, 'total', sum(n.values()))
