// The hand-written part of the SDK 1.48 shim (gen.py generates the rest from steam_api.json).
// Written from the public SDK headers only: 1.48's (compiled against) and the newer SDK's
// declarations of the two core entry points used below.
#include <string.h>
#include "steam/steam_api.h"
#include "steam/steam_gameserver.h"
#include "isteamtv148.h"  // generated by gen.py; must precede steam_api_flat.h
#include "steam/steam_api_flat.h"  // definitions below must match 1.48's flat declarations
#define SHIM extern "C" __attribute__((visibility("default")))  // 1.48's S_API exports nothing outside Valve's build

// Exported by the newer core (libsteam_api_core.dylib); declarations as in its SDK's
// steam_api_common.h, steam_api.h and steam_gameserver.h. None of these exist in 1.48.
typedef char SteamErrMsg[1024];
enum ESteamAPIInitResult
{
	k_ESteamAPIInitResult_OK = 0,
	k_ESteamAPIInitResult_FailedGeneric = 1,
	k_ESteamAPIInitResult_NoSteamClient = 2,
	k_ESteamAPIInitResult_VersionMismatch = 3,
};
S_API ESteamAPIInitResult S_CALLTYPE SteamAPI_InitFlat( SteamErrMsg *pOutErrMsg );
S_API ESteamAPIInitResult S_CALLTYPE SteamInternal_GameServer_Init_V2( uint32 unIP, uint16 usGamePort, uint16 usQueryPort, EServerMode eServerMode,
	const char *pchVersionString, const char *pszInternalCheckInterfaceVersions, SteamErrMsg *pOutErrMsg );

// The newer core removed the 1.48 export. SteamAPI_InitFlat is its init for callers that can't use the
// C++ header, so it does not check interface versions against the newer SDK (we use 1.48's).
SHIM bool S_CALLTYPE SteamAPI_Init()
{
	SteamErrMsg err;
	return SteamAPI_InitFlat( &err ) == k_ESteamAPIInitResult_OK;
}

// 1.48 signature -> _V2. The Steam port was already ignored in 1.48 ("you should pass 0") and _V2
// dropped it. The interface check list is NUL-separated and ends with an empty string: pass an
// empty list, since the newer SDK's versions are not the ones this shim uses.
SHIM bool S_CALLTYPE SteamInternal_GameServer_Init( uint32 unIP, uint16 /*usLegacySteamPort*/, uint16 usGamePort, uint16 usQueryPort,
	EServerMode eServerMode, const char *pchVersionString )
{
	SteamErrMsg err;
	return SteamInternal_GameServer_Init_V2( unIP, usGamePort, usQueryPort, eServerMode, pchVersionString, "", &err ) == k_ESteamAPIInitResult_OK;
}

// 1.48's steam_api_flat.h declares these, but its steamnetworkingtypes.h has neither the methods nor the
// identity type. Per the header's layout: type 17 (k_ESteamNetworkingIdentityType_XboxPairwiseID), the
// string NUL-terminated at the start of the identity's union, m_cbSize = strlen + 1. Set rejects empty and
// too-long strings. Valve's 1.48 lib caps it at 32 bytes including the NUL, like 1.48's generic string
// (later SDKs: k_cchMaxXboxPairwiseID = 33); black-box tested by difftest.c.
static const ESteamNetworkingIdentityType k_eXboxPairwiseID = ESteamNetworkingIdentityType( 17 );
static const size_t k_cchMaxXboxPairwiseID = SteamNetworkingIdentity::k_cchMaxGenericString;

SHIM bool SteamAPI_SteamNetworkingIdentity_SetXboxPairwiseID( SteamNetworkingIdentity* self, const char * pszString )
{
	size_t l = strlen( pszString );
	if ( l < 1 || l >= k_cchMaxXboxPairwiseID )
		return false;
	self->m_eType = k_eXboxPairwiseID;
	self->m_cbSize = int( l + 1 );
	memcpy( self->m_szUnknownRawString, pszString, l + 1 );
	return true;
}

SHIM const char * SteamAPI_SteamNetworkingIdentity_GetXboxPairwiseID( SteamNetworkingIdentity* self )
{
	return self->m_eType == k_eXboxPairwiseID ? self->m_szUnknownRawString : NULL;
}
