<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    <Nullable>disable</Nullable>
    <NoWarn>MSB3277</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Facepunch.Steamworks.Win64" HintPath="../out/Facepunch.Steamworks.Win64.dll" />
    <None Include="../out/libsteam_api.dylib;../out/libsteam_api_core.dylib;../reexports.txt" CopyToOutputDirectory="PreserveNewest" Link="%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
